"""
News sources configuration for the scraper.
Defines the list of news sources and their RSS feeds.
Generated by validate_feeds.py on 2025-05-14
"""

import os
import json
import logging
from typing import List, Dict, Any

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

def get_news_sources() -> List[Dict[str, Any]]:
    """
    Get the list of news sources with their RSS feeds.
    
    Returns:
        List of news source dictionaries with name, country, language, and RSS feeds
    """
    # Define the comprehensive set of news sources from around the world
    news_sources = [
        {
            "name": "CNN",
            "country": "USA",
            "language": "en",
            "rss_feeds": [
                "http://rss.cnn.com/rss/cnn_topstories.rss",
                "http://rss.cnn.com/rss/cnn_world.rss",
                "http://rss.cnn.com/rss/cnn_us.rss",
                "http://rss.cnn.com/rss/money_latest.rss",
                "http://rss.cnn.com/rss/cnn_allpolitics.rss",
            ]
        },
        {
            "name": "Fox News",
            "country": "USA",
            "language": "en",
            "rss_feeds": [
                "https://moxie.foxnews.com/google-publisher/latest.xml",
                "https://moxie.foxnews.com/google-publisher/politics.xml",
                "https://moxie.foxnews.com/google-publisher/world.xml",
            ]
        },
        {
            "name": "The New York Times",
            "country": "USA",
            "language": "en",
            "rss_feeds": [
                "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml",
                "https://rss.nytimes.com/services/xml/rss/nyt/World.xml",
                "https://rss.nytimes.com/services/xml/rss/nyt/US.xml",
                "https://rss.nytimes.com/services/xml/rss/nyt/Politics.xml",
            ]
        },
        {
            "name": "NPR",
            "country": "USA",
            "language": "en",
            "rss_feeds": [
                "https://feeds.npr.org/1001/rss.xml",
                "https://feeds.npr.org/1003/rss.xml",
                "https://feeds.npr.org/1014/rss.xml",
            ]
        },
        {
            "name": "CBC News",
            "country": "Canada",
            "language": "en",
            "rss_feeds": [
                "https://rss.cbc.ca/lineup/topstories.xml",
                "https://rss.cbc.ca/lineup/world.xml",
                "https://rss.cbc.ca/lineup/politics.xml",
            ]
        },
        {
            "name": "The Globe and Mail",
            "country": "Canada",
            "language": "en",
            "rss_feeds": [
                "https://www.theglobeandmail.com/arc/outboundfeeds/rss/category/politics/",
                "https://www.theglobeandmail.com/arc/outboundfeeds/rss/category/world/",
            ]
        },
        {
            "name": "National Post",
            "country": "Canada",
            "language": "en",
            "rss_feeds": [
                "https://nationalpost.com/feed/",
            ]
        },
        {
            "name": "Toronto Star",
            "country": "Canada",
            "language": "en",
            "rss_feeds": [
                "https://www.thestar.com/feeds/articles.rss",
                "https://www.thestar.com/content/thestar/feed.RSSManagerServlet.topstories.rss",
            ]
        },
        {
            "name": "BBC",
            "country": "UK",
            "language": "en",
            "rss_feeds": [
                "http://feeds.bbci.co.uk/news/rss.xml",
                "http://feeds.bbci.co.uk/news/world/rss.xml",
                "http://feeds.bbci.co.uk/news/politics/rss.xml",
                "http://feeds.bbci.co.uk/news/business/rss.xml",
            ]
        },
        {
            "name": "The Guardian",
            "country": "UK",
            "language": "en",
            "rss_feeds": [
                "https://www.theguardian.com/international/rss",
                "https://www.theguardian.com/uk/rss",
                "https://www.theguardian.com/politics/rss",
                "https://www.theguardian.com/world/rss",
            ]
        },
        {
            "name": "Sky News",
            "country": "UK",
            "language": "en",
            "rss_feeds": [
                "https://feeds.skynews.com/feeds/rss/home.xml",
                "https://feeds.skynews.com/feeds/rss/world.xml",
                "https://feeds.skynews.com/feeds/rss/politics.xml",
            ]
        },
        {
            "name": "The Independent",
            "country": "UK",
            "language": "en",
            "rss_feeds": [
                "https://www.independent.co.uk/news/world/rss",
                "https://www.independent.co.uk/news/uk/rss",
            ]
        },
        {
            "name": "Deutsche Welle",
            "country": "Germany",
            "language": "en",
            "rss_feeds": [
                "https://rss.dw.com/rdf/rss-en-all",
                "https://rss.dw.com/rdf/rss-en-world",
            ]
        },
        {
            "name": "Der Spiegel",
            "country": "Germany",
            "language": "en",
            "rss_feeds": [
                "https://www.spiegel.de/international/index.rss",
            ]
        },
        {
            "name": "France 24",
            "country": "France",
            "language": "en",
            "rss_feeds": [
                "https://www.france24.com/en/rss",
            ]
        },
        {
            "name": "RT",
            "country": "Russia",
            "language": "en",
            "rss_feeds": [
                "https://www.rt.com/rss/",
            ]
        },
        {
            "name": "TASS",
            "country": "Russia",
            "language": "en",
            "rss_feeds": [
                "https://tass.com/rss/v2.xml",
            ]
        },
        {
            "name": "Sputnik News",
            "country": "Russia",
            "language": "en",
            "rss_feeds": [
                "https://sputniknews.com/export/rss2/world/index.xml",
            ]
        },
        {
            "name": "Euronews",
            "country": "EU",
            "language": "en",
            "rss_feeds": [
                "https://www.euronews.com/rss",
            ]
        },
        {
            "name": "RTE News",
            "country": "Ireland",
            "language": "en",
            "rss_feeds": [
                "https://www.rte.ie/news/rss/news-headlines.xml",
            ]
        },
        {
            "name": "Al Jazeera",
            "country": "Qatar",
            "language": "en",
            "rss_feeds": [
                "https://www.aljazeera.com/xml/rss/all.xml",
            ]
        },
        {
            "name": "Jerusalem Post",
            "country": "Israel",
            "language": "en",
            "rss_feeds": [
                "https://www.jpost.com/rss/front-page",
            ]
        },
        {
            "name": "Haaretz",
            "country": "Israel",
            "language": "en",
            "rss_feeds": [
                "https://www.haaretz.com/cmlink/1.4605045",
            ]
        },
        {
            "name": "Times of Israel",
            "country": "Israel",
            "language": "en",
            "rss_feeds": [
                "https://www.timesofisrael.com/feed/",
            ]
        },
        {
            "name": "Gulf News",
            "country": "UAE",
            "language": "en",
            "rss_feeds": [
                "https://gulfnews.com/feed",
            ]
        },
        {
            "name": "Arab News",
            "country": "Saudi Arabia",
            "language": "en",
            "rss_feeds": [
                "https://www.arabnews.com/rss.xml",
            ]
        },
        {
            "name": "Anadolu Agency",
            "country": "Turkey",
            "language": "en",
            "rss_feeds": [
                "https://www.aa.com.tr/en/rss/default?cat=world",
            ]
        },
        {
            "name": "Dawn",
            "country": "Pakistan",
            "language": "en",
            "rss_feeds": [
                "https://www.dawn.com/feed",
            ]
        },
        {
            "name": "The Express Tribune",
            "country": "Pakistan",
            "language": "en",
            "rss_feeds": [
                "https://tribune.com.pk/feed/latest",
            ]
        },
        {
            "name": "The Times of India",
            "country": "India",
            "language": "en",
            "rss_feeds": [
                "https://timesofindia.indiatimes.com/rssfeeds/296589292.cms",
                "https://timesofindia.indiatimes.com/rssfeeds/1081479906.cms",
            ]
        },
        {
            "name": "The Hindu",
            "country": "India",
            "language": "en",
            "rss_feeds": [
                "https://www.thehindu.com/news/national/feeder/default.rss",
                "https://www.thehindu.com/news/international/feeder/default.rss",
            ]
        },
        {
            "name": "Hindustan Times",
            "country": "India",
            "language": "en",
            "rss_feeds": [
                "https://www.hindustantimes.com/feeds/rss/world-news/rssfeed.xml",
                "https://www.hindustantimes.com/feeds/rss/india-news/rssfeed.xml",
            ]
        },
        {
            "name": "South China Morning Post",
            "country": "Hong Kong/China",
            "language": "en",
            "rss_feeds": [
                "https://www.scmp.com/rss/91/feed",
            ]
        },
        {
            "name": "China Daily",
            "country": "China",
            "language": "en",
            "rss_feeds": [
                "https://www.chinadaily.com.cn/rss/world_rss.xml",
            ]
        },
        {
            "name": "Global Times",
            "country": "China",
            "language": "en",
            "rss_feeds": [
                "https://www.globaltimes.cn/rss/world.xml",
            ]
        },
        {
            "name": "Xinhua News",
            "country": "China",
            "language": "en",
            "rss_feeds": [
                "http://www.xinhuanet.com/english/rss/worldrss.xml",
            ]
        },
        {
            "name": "People's Daily",
            "country": "China",
            "language": "en",
            "rss_feeds": [
                "http://en.people.cn/rss/World.xml",
            ]
        },
        {
            "name": "CGTN",
            "country": "China",
            "language": "en",
            "rss_feeds": [
                "https://www.cgtn.com/subscribe/rss/section/world.xml",
            ]
        },
        {
            "name": "China News Service",
            "country": "China",
            "language": "en",
            "rss_feeds": [
                "http://www.ecns.cn/rss/news.xml",
            ]
        },
        {
            "name": "The Japan Times",
            "country": "Japan",
            "language": "en",
            "rss_feeds": [
                "https://www.japantimes.co.jp/feed/",
            ]
        },
        {
            "name": "NHK World",
            "country": "Japan",
            "language": "en",
            "rss_feeds": [
                "https://www3.nhk.or.jp/rss/news/cat0.xml",
            ]
        },
        {
            "name": "Kyodo News",
            "country": "Japan",
            "language": "en",
            "rss_feeds": [
                "https://english.kyodonews.net/rss/all.xml",
            ]
        },
        {
            "name": "Asahi Shimbun",
            "country": "Japan",
            "language": "en",
            "rss_feeds": [
                "https://rss.asahi.com/rss/asahi/newsheadlines.rdf",
            ]
        },
        {
            "name": "The Korea Times",
            "country": "South Korea",
            "language": "en",
            "rss_feeds": [
                "https://www.koreatimes.co.kr/www/rss/rss.xml",
            ]
        },
        {
            "name": "Korea Herald",
            "country": "South Korea",
            "language": "en",
            "rss_feeds": [
                "https://www.koreaherald.com/rss_xml.php",
            ]
        },
        {
            "name": "Yonhap News",
            "country": "South Korea",
            "language": "en",
            "rss_feeds": [
                "https://en.yna.co.kr/RSS/news.xml",
            ]
        },
        {
            "name": "The Straits Times",
            "country": "Singapore",
            "language": "en",
            "rss_feeds": [
                "https://www.straitstimes.com/news/world/rss.xml",
                "https://www.straitstimes.com/news/asia/rss.xml",
            ]
        },
        {
            "name": "News24",
            "country": "South Africa",
            "language": "en",
            "rss_feeds": [
                "https://www.news24.com/rss/feed",
            ]
        },
        {
            "name": "Mail & Guardian",
            "country": "South Africa",
            "language": "en",
            "rss_feeds": [
                "https://mg.co.za/feed/",
            ]
        },
        {
            "name": "AllAfrica",
            "country": "Pan-African",
            "language": "en",
            "rss_feeds": [
                "https://allafrica.com/tools/headlines/rdf/latest/headlines.rdf",
            ]
        },
        {
            "name": "The East African",
            "country": "East Africa",
            "language": "en",
            "rss_feeds": [
                "https://www.theeastafrican.co.ke/articlefeeds/1447302/1447302-view-asFeed-u2uktcz/index.xml",
            ]
        },
        {
            "name": "ABC News (Australia)",
            "country": "Australia",
            "language": "en",
            "rss_feeds": [
                "https://www.abc.net.au/news/feed/51120/rss.xml",
            ]
        },
        {
            "name": "The Sydney Morning Herald",
            "country": "Australia",
            "language": "en",
            "rss_feeds": [
                "https://www.smh.com.au/rss/world.xml",
            ]
        },
        {
            "name": "The Age",
            "country": "Australia",
            "language": "en",
            "rss_feeds": [
                "https://www.theage.com.au/rss/feed.xml",
                "https://www.theage.com.au/rss/world.xml",
                "https://www.theage.com.au/rss/national.xml",
            ]
        },
        {
            "name": "New Zealand Herald",
            "country": "New Zealand",
            "language": "en",
            "rss_feeds": [
                "https://www.nzherald.co.nz/rss/world/",
            ]
        },
        {
            "name": "Politico",
            "country": "USA",
            "language": "en",
            "rss_feeds": [
                "https://www.politico.com/rss/politics08.xml",
                "https://www.politico.com/rss/world.xml",
            ]
        },
        {
            "name": "United Nations",
            "country": "International",
            "language": "en",
            "rss_feeds": [
                "https://news.un.org/feed/subscribe/en/news/all/rss.xml",
            ]
        },
        {
            "name": "ABC News (US)",
            "country": "USA",
            "language": "en",
            "rss_feeds": [
                "https://abcnews.go.com/abcnews/topstories",
                "https://abcnews.go.com/abcnews/politicsheadlines",
                "https://abcnews.go.com/abcnews/usheadlines",
                "https://abcnews.go.com/abcnews/internationalheadlines",
            ]
        },
        {
            "name": "Foreign Affairs",
            "country": "USA",
            "language": "en",
            "rss_feeds": [
                "https://www.foreignaffairs.com/rss.xml",
            ]
        },
        {
            "name": "Globe and Mail",
            "country": "Canada",
            "language": "en",
            "rss_feeds": [
                "https://www.theglobeandmail.com/arc/outboundfeeds/rss/category/news/",
            ]
        },
        {
            "name": "Der Spiegel",
            "country": "Germany",
            "language": "de",
            "rss_feeds": [
                "https://www.spiegel.de/international/index.rss",
                "https://www.spiegel.de/schlagzeilen/index.rss",
            ]
        },
        {
            "name": "Frankfurter Allgemeine Zeitung",
            "country": "Germany",
            "language": "de",
            "rss_feeds": [
                "https://www.faz.net/rss/aktuell/",
            ]
        },
        {
            "name": "Le Monde",
            "country": "France",
            "language": "fr",
            "rss_feeds": [
                "https://www.lemonde.fr/rss/une.xml",
                "https://www.lemonde.fr/international/rss_full.xml",
            ]
        },
        {
            "name": "Le Figaro",
            "country": "France",
            "language": "fr",
            "rss_feeds": [
                "https://www.lefigaro.fr/rss/figaro_actualites.xml",
                "https://www.lefigaro.fr/rss/figaro_international.xml",
            ]
        },
        {
            "name": "Corriere della Sera",
            "country": "Italy",
            "language": "it",
            "rss_feeds": [
                "https://xml2.corriereobjects.it/rss/homepage.xml",
                "https://xml2.corriereobjects.it/rss/esteri.xml",
            ]
        },
        {
            "name": "La Repubblica",
            "country": "Italy",
            "language": "it",
            "rss_feeds": [
                "https://www.repubblica.it/rss/homepage/rss2.0.xml",
            ]
        },
        {
            "name": "El País",
            "country": "Spain",
            "language": "es",
            "rss_feeds": [
                "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada",
                "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/internacional",
            ]
        },
        {
            "name": "El Mundo",
            "country": "Spain",
            "language": "es",
            "rss_feeds": [
                "https://e00-elmundo.uecdn.es/elmundo/rss/portada.xml",
            ]
        },
        {
            "name": "The Australian",
            "country": "Australia",
            "language": "en",
            "rss_feeds": [
                "https://www.theaustralian.com.au/rss/",
            ]
        },
        {
            "name": "Folha de S.Paulo",
            "country": "Brazil",
            "language": "pt",
            "rss_feeds": [
                "https://feeds.folha.uol.com.br/emcimadahora/rss091.xml",
            ]
        },
        {
            "name": "O Globo",
            "country": "Brazil",
            "language": "pt",
            "rss_feeds": [
                "https://oglobo.globo.com/rss.xml",
            ]
        },
        {
            "name": "The Times",
            "country": "UK",
            "language": "en",
            "rss_feeds": [
                "https://www.thetimes.co.uk/rss",
            ]
        },
        {
            "name": "Financial Times",
            "country": "UK",
            "language": "en",
            "rss_feeds": [
                "https://www.ft.com/rss/home",
            ]
        },
        {
            "name": "Die Zeit",
            "country": "Germany",
            "language": "de",
            "rss_feeds": [
                "https://newsfeed.zeit.de/index",
                "https://newsfeed.zeit.de/politik/index",
            ]
        },
        {
            "name": "Die Welt",
            "country": "Germany",
            "language": "de",
            "rss_feeds": [
                "https://www.welt.de/feeds/latest.rss",
                "https://www.welt.de/feeds/topthemen.rss",
            ]
        },
        {
            "name": "Süddeutsche Zeitung",
            "country": "Germany",
            "language": "de",
            "rss_feeds": [
                "https://www.sueddeutsche.de/news/rss",
                "https://www.sueddeutsche.de/politik/rss",
            ]
        },
        {
            "name": "France 24",
            "country": "France",
            "language": "fr",
            "rss_feeds": [
                "https://www.france24.com/fr/rss",
                "https://www.france24.com/fr/actualites/rss",
            ]
        },
        {
            "name": "BFM TV",
            "country": "France",
            "language": "fr",
            "rss_feeds": [
                "https://www.bfmtv.com/rss/info/flux-rss/flux-toutes-les-actualites/",
            ]
        },
        {
            "name": "Libération",
            "country": "France",
            "language": "fr",
            "rss_feeds": [
                "https://www.liberation.fr/arc/outboundfeeds/rss-all/",
            ]
        },
        {
            "name": "La Gazzetta del Mezzogiorno",
            "country": "Italy",
            "language": "it",
            "rss_feeds": [
                "https://www.lagazzettadelmezzogiorno.it/rss/",
            ]
        },
        {
            "name": "ANSA",
            "country": "Italy",
            "language": "it",
            "rss_feeds": [
                "https://www.ansa.it/sito/notizie/topnews/topnews_rss.xml",
                "https://www.ansa.it/sito/notizie/mondo/mondo_rss.xml",
            ]
        },
        {
            "name": "ABC España",
            "country": "Spain",
            "language": "es",
            "rss_feeds": [
                "https://www.abc.es/rss/feeds/abcPortada.xml",
                "https://www.abc.es/rss/feeds/abcInternacional.xml",
            ]
        },
        {
            "name": "La Vanguardia",
            "country": "Spain",
            "language": "es",
            "rss_feeds": [
                "https://www.lavanguardia.com/rss/home.xml",
                "https://www.lavanguardia.com/rss/internacional.xml",
            ]
        },
        {
            "name": "Público Portugal",
            "country": "Portugal",
            "language": "pt",
            "rss_feeds": [
                "https://www.publico.pt/rss",
            ]
        },
        {
            "name": "Observador",
            "country": "Portugal",
            "language": "pt",
            "rss_feeds": [
                "https://observador.pt/feed/",
            ]
        },
        {
            "name": "Mainichi Shimbun",
            "country": "Japan",
            "language": "ja",
            "rss_feeds": [
                "https://mainichi.jp/rss/etc/mainichi-flash.rss",
            ]
        },
        {
            "name": "Yomiuri Shimbun",
            "country": "Japan",
            "language": "ja",
            "rss_feeds": [
                "https://www.yomiuri.co.jp/rss/",
            ]
        },
        {
            "name": "Chosun Ilbo",
            "country": "South Korea",
            "language": "ko",
            "rss_feeds": [
                "https://www.chosun.com/arc/outboundfeeds/rss/",
            ]
        },
        {
            "name": "Hankyoreh",
            "country": "South Korea",
            "language": "ko",
            "rss_feeds": [
                "https://www.hani.co.kr/rss/",
            ]
        },
        {
            "name": "Caixin",
            "country": "China",
            "language": "zh",
            "rss_feeds": [
                "https://www.caixin.com/rss/all.xml",
            ]
        },
        {
            "name": "El Universal México",
            "country": "Mexico",
            "language": "es",
            "rss_feeds": [
                "https://www.eluniversal.com.mx/rss.xml",
            ]
        },
        {
            "name": "La Jornada",
            "country": "Mexico",
            "language": "es",
            "rss_feeds": [
                "https://www.jornada.com.mx/rss/portada.xml",
            ]
        },
        {
            "name": "Clarín",
            "country": "Argentina",
            "language": "es",
            "rss_feeds": [
                "https://www.clarin.com/rss.xml",
            ]
        },
        {
            "name": "La Nación Argentina",
            "country": "Argentina",
            "language": "es",
            "rss_feeds": [
                "https://www.lanacion.com.ar/rss",
            ]
        },
        {
            "name": "El Mercurio",
            "country": "Chile",
            "language": "es",
            "rss_feeds": [
                "https://www.emol.com/rss/rss.asp?canal=1",
            ]
        },
        {
            "name": "NOS",
            "country": "Netherlands",
            "language": "nl",
            "rss_feeds": [
                "https://feeds.nos.nl/nosnieuwsalgemeen",
                "https://feeds.nos.nl/nosnieuwsbuitenland",
            ]
        },
        {
            "name": "De Volkskrant",
            "country": "Netherlands",
            "language": "nl",
            "rss_feeds": [
                "https://www.volkskrant.nl/rss/voorpagina",
            ]
        },
        {
            "name": "Svenska Dagbladet",
            "country": "Sweden",
            "language": "sv",
            "rss_feeds": [
                "https://www.svd.se/rss.xml",
            ]
        },
        {
            "name": "Dagens Nyheter",
            "country": "Sweden",
            "language": "sv",
            "rss_feeds": [
                "https://www.dn.se/rss/",
            ]
        },
        {
            "name": "VG",
            "country": "Norway",
            "language": "no",
            "rss_feeds": [
                "https://www.vg.no/rss/create.php?categories=1068,1069,1078",
            ]
        },
        {
            "name": "Aftenposten",
            "country": "Norway",
            "language": "no",
            "rss_feeds": [
                "https://www.aftenposten.no/rss/",
            ]
        },
        {
            "name": "Politiken",
            "country": "Denmark",
            "language": "da",
            "rss_feeds": [
                "https://politiken.dk/rss/senestenyt.rss",
            ]
        },
        {
            "name": "Helsingin Sanomat",
            "country": "Finland",
            "language": "fi",
            "rss_feeds": [
                "https://www.hs.fi/rss/tuoreimmat.xml",
            ]
        },
        {
            "name": "Neue Zürcher Zeitung",
            "country": "Switzerland",
            "language": "de",
            "rss_feeds": [
                "https://www.nzz.ch/recent.rss",
            ]
        },
        {
            "name": "Der Standard",
            "country": "Austria",
            "language": "de",
            "rss_feeds": [
                "https://www.derstandard.at/rss",
            ]
        },
        {
            "name": "De Standaard",
            "country": "Belgium",
            "language": "nl",
            "rss_feeds": [
                "https://www.standaard.be/rss/section/1f2838d4-99ea-49f0-9102-138784c7ea7c",
            ]
        },
        {
            "name": "Ynet",
            "country": "Israel",
            "language": "he",
            "rss_feeds": [
                "https://www.ynet.co.il/Integration/StoryRss1854.xml",
            ]
        },
        {
            "name": "Al Arabiya",
            "country": "UAE",
            "language": "ar",
            "rss_feeds": [
                "https://www.alarabiya.net/rss/feeds/web/news.xml",
            ]
        },
        {
            "name": "Al Ahram",
            "country": "Egypt",
            "language": "ar",
            "rss_feeds": [
                "https://www.ahram.org.eg/rss/ahram.xml",
            ]
        },
        {
            "name": "Middle East Eye",
            "country": "UK",
            "language": "en",
            "rss_feeds": [
                "https://www.middleeasteye.net/rss.xml",
            ]
        },
        {
            "name": "Fox Business",
            "country": "USA",
            "language": "en",
            "rss_feeds": [
                "https://moxie.foxbusiness.com/google-publisher/latest.xml",
            ]
        },
    ]

    
    # Try to load custom news sources from a JSON file if it exists
    custom_sources_path = os.path.join(os.path.dirname(__file__), 'custom_news_sources.json')
    if os.path.exists(custom_sources_path):
        try:
            with open(custom_sources_path, 'r') as f:
                custom_sources = json.load(f)
                logger.info(f"Loaded {len(custom_sources)} custom news sources")
                news_sources.extend(custom_sources)
        except Exception as e:
            logger.error(f"Error loading custom news sources: {e}")
    
    logger.info(f"Total news sources: {len(news_sources)}")
    return news_sources

def add_news_source(name: str, country: str, language: str, rss_feeds: List[str]) -> bool:
    """
    Add a new news source to the custom sources file.
    
    Args:
        name: Name of the news source
        country: Country of origin
        language: Language code (e.g., 'en')
        rss_feeds: List of RSS feed URLs
        
    Returns:
        True if the source was added successfully, False otherwise
    """
    custom_sources_path = os.path.join(os.path.dirname(__file__), 'custom_news_sources.json')
    
    # Load existing custom sources or create an empty list
    custom_sources = []
    if os.path.exists(custom_sources_path):
        try:
            with open(custom_sources_path, 'r') as f:
                custom_sources = json.load(f)
        except Exception as e:
            logger.error(f"Error loading custom news sources: {e}")
    
    # Check if source already exists
    for source in custom_sources:
        if source.get('name') == name:
            logger.warning(f"News source '{name}' already exists")
            return False
    
    # Add the new source
    custom_sources.append({
        "name": name,
        "country": country,
        "language": language,
        "rss_feeds": rss_feeds
    })
    
    # Save the updated list
    try:
        with open(custom_sources_path, 'w') as f:
            json.dump(custom_sources, f, indent=2)
        logger.info(f"Added news source: {name}")
        return True
    except Exception as e:
        logger.error(f"Error saving custom news sources: {e}")
        return False

if __name__ == "__main__":
    # When run directly, print out the configured news sources
    sources = get_news_sources()
    print(f"Configured {len(sources)} news sources:")
    
    # Count sources by region
    regions = {}
    for source in sources:
        country = source['country']
        regions[country] = regions.get(country, 0) + 1
    
    print("\nSources by country:")
    for country, count in sorted(regions.items(), key=lambda x: x[1], reverse=True):
        print(f"  {country}: {count} sources")
        
    print("\nSome of the available sources:")
    for i, source in enumerate(sources[:10], 1):
        feed_count = len(source.get('rss_feeds', []))
        print(f"  {i}. {source['name']} ({source['country']}, {source['language']}): {feed_count} feeds")
